name: Compile PDFs

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Compile
      run: make resume

    - uses: actions/upload-artifact@v4
      with:
        name: project
        path: project/JoshOberhaus.pdf
